spring:
  application:
    name: project_demo

  profiles:
    active: ${APP_PROFILE:dev}

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    disable-swagger-default-url: true
    operations-sorter: alpha
    tags-sorter: alpha

server:
  port: 8080

app:
  jwt:
    issuer: yoedu-demo
    secret: xveViUZs13YjF2h5jzcJqkL619kstdRvgxcXSiH3pN6fsUQi5PDA0wB6ah8pDPlTP
    access-token-ttl-minutes: 480
    refresh-token-ttl-days: 7